#! Deployment definition for Wireguard Easy,
#! It mounts the /lib/module unix directory so that kernel module for wireguard can be accessed.
#! Also, it mounts a path for storing wg0.conf with the peer and server configurations.
#! The management web interface on port 51821 and the DNS port 51820
kind: Deployment
apiVersion: apps/v1
metadata:
  name: wireguard
  namespace: kubeguard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubeguard
  template:
    metadata:
      labels:
        app: kubeguard
    spec:
      containers:
      - name: wireguard
        image: weejewel/wg-easy
        ports:
        - containerPort: 51820
          protocol: UDP
        - containerPort: 51821
          protocol: TCP
        resources:
          requests:
            cpu: "512m"
            memory: "256Mi"
          limits:
            cpu: "768m"
            memory: "512Mi"
        env:
        - name: WG_HOST
          value: localhost
        - name: WG_DEFAULT_DNS
          value: 1.1.1.1
        - name: PASSWORD
          value: asdfghjk
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
            - SYS_MODULE
        volumeMounts:
        - name: wireguard-volume # stores wg-easy configuration 
          mountPath: /etc/wireguard
        - name: lib-volume
          mountPath: /lib/modules # makes available wireguard module to pod, this may not be required
      volumes:
      - name: wireguard-volume
        hostPath:
          path: /mnt/k3s/wireguard
      - name: lib-volume
        hostPath:
          path: /lib/modules

