---
#! Service definition for all Kubeguard Components, being: 
apiVersion: v1
kind: Service
metadata:
  name: kubeguard
  namespace: kubeguard
  labels:
    app: kubeguard
spec:
  type: LoadBalancer
  selector:
    app: kubeguard
  ports:
  - name: domain-name-service
    port: 53
    targetPort: 53
    protocol: UDP
  - name: adguard-console
    port: 3000
    targetPort: 3000
    protocol: TCP  
  - name: wireguard-vpn
    port: 51820
    targetPort: 51820
    protocol: UDP
  - name: wireguard-console
    port: 51821
    targetPort: 51821
    protocol: TCP
  